# Dev stage
FROM node:22-alpine AS dev

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

EXPOSE 4000

CMD ["yarn", "run", "dev"]

# Prod stage
FROM node:22-alpine AS prod

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

EXPOSE 4000

CMD ["yarn", "start"]
